### ISSUE TITLE
Improve Error Handling in useFetchBooks Hook

### ISSUE THREAD

**Issue by livoszlak** [livoszlak/book-finder-api-2.0#1]
Enhance the error handling in the [useFetchBooks](https://github.com/livoszlak/book-finder-api-2.0/blob/main/src/hooks/useFetchBooks.js) hook to provide more detailed error messages and possibly retry logic.

**Comment by om9090** [comment]
Hi @livoszlak I would love to work on the issue. I can definitely help you overcome it by better error handling. Please assign it to me.

**Comment by livoszlak** [comment]
@om9090 Thank you, that would be awesome! Consider yourself assigned. 🙂

**Comment by om9090** [comment]
Yes thank you I’ll start working on it
