### ISSUE TITLE
Add Loading Spinner to Book Search

### ISSUE THREAD

**Issue by livoszlak** [livoszlak/book-finder-api-2.0#5]
Add a loading spinner to the [BookSearch](https://github.com/livoszlak/book-finder-api-2.0/blob/main/src/components/BookSearch.jsx) component to improve user experience while waiting for search results. There are probably nice alternatives within the MUI library!

**Comment by HarshitT00** [comment]
I want to work on this could you please assign it to me?

**Comment by livoszlak** [comment]
> I want to work on this could you please assign it to me?

Absolutely! Thank you!

**Comment by HarshitT00** [comment]
Added a pull request could you have a look

**Comment by livoszlak** [comment]
> Added a pull request could you have a look

Checked and merged! Thank you so much for contributing! 🙌
