### ISSUE TITLE
Add Ternary for Displaying Placeholder If Book Lacks Cover

### ISSUE THREAD

**Issue by livoszlak** [livoszlak/book-finder-api-2.0#7]
Sometimes the results from the API don't contain a cover image for the book. This means the BookItem just has a broken image link and displays the alt text. I would like a placeholder icon in place of the non-existent cover img. Maybe the ImageNotSupported icon from MUI could work. If you want to work in another ternary for the icon to have a "Placeholder icon: cover for [book.title] not found" as alt text, that works.

**Comment by Sarveshk76** [comment]
Hi @livoszlak, I would like to work on this

**Comment by livoszlak** [comment]
@Sarveshk76 Absolutely! I'll assign you right away. Thank you! 🌷
